apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hem-gateway
spec:
  selector:
    istio: ingress       # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: {{ .Values.ingressHostList }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts: {{ .Values.ingressHostList }}
  gateways:
    - hem-gateway
  http:
    route:
    - destination:
        host: prometheus-grafana.monitoring.svc.cluster.local
        port:
          number: 80

